% JSON Generator

%-------------------------------------------------------------------------%
% ## BUTTONS ##
%-------------------------------------------------------------------------%
% BUTTON
% C:\Program Files\MATLAB\R2022b\toolbox\matlab\toolstrip\+matlab\+ui\+internal\+toolstrip\Button.m
% Input arguments: "text", or "icon"
% btn = Button('Open', Icon.OPEN_24);
% btn.ButtonPushed = {@callbacks.openButtonPushed, this};

% DROPDOWNBUTTON / POPUPLIST / LISTITEM
% Input arguments: "text", or "icon"
% btn = matlab.ui.internal.toolstrip.DropDownButton(text,icon)
%
% sub_item1 = matlab.ui.internal.toolstrip.ListItem('Add Plot');
% sub_item1.ItemPushed = {@callbacks.subItem1Pushed, this};
% sub_item2 = matlab.ui.internal.toolstrip.ListItem('Delete Plot');
% sub_item2.ItemPushed = {@callbacks.subItem2Pushed, this};
%
% sub_popup = matlab.ui.internal.toolstrip.PopupList();
% sub_popup.add(sub_item1);
% sub_popup.add(sub_item2);
% 
% item1 = matlab.ui.internal.toolstrip.ListItem('Add Plot',matlab.ui.internal.toolstrip.Icon.ADD_16);
% item1.ItemPushed = {@callbacks.Item1Pushed, this};
%
% item2 = matlab.ui.internal.toolstrip.ListItemWithPopup('Delete Plot',matlab.ui.internal.toolstrip.Icon.CUT_16);
% item2.Popup = sub_popup;
% 
% popup = matlab.ui.internal.toolstrip.PopupList();
% popup.add(item1);
% popup.add(item2);
% 
% btn.Popup = popup;


% BUTTONGROUP - Radio buttons or toggle buttons in this group can only be selected one at a time.
% C:\Program Files\MATLAB\R2022b\toolbox\matlab\toolstrip\+matlab\+ui\+internal\+toolstrip\ButtonGroup.m
% group1 = ButtonGroup();
% btn1 = RadioButton(group1, 'Radio button 1');
% btn2 = RadioButton(group2, 'Radio button 2');

% TOGGLEBUTTON
% C:\Program Files\MATLAB\R2022b\toolbox\matlab\toolstrip\+matlab\+ui\+internal\+toolstrip\ToggleButton.m
% Input arguments: "text", "icon", or "group"
% btn = ToggleButton('Open', Icon.OPEN_24, Group1);
% btn.ValueChanged = {@callbacks.openButtonPushed, this};

% RADIOBUTTON
% C:\Program Files\MATLAB\R2022b\toolbox\matlab\toolstrip\+matlab\+ui\+internal\+toolstrip\RadioButton.m
% Input arguments: "group", and "text"
% btn = RadioButton(group, text);

TabStruct  = struct('HOME', {{'File', 'Edit'}}, ...
                    'PLOT', {{'Playback', 'xy-Limits', 'Controls', 'Persistance', 'Occupancy', 'Waterfall'}}, ...
                    'EMISSION', {{'Add/List', 'Detection type', 'FindPeaks parameters', 'Miscellaneous'}});

%-------------------------------------------------------------------------%
% TAB 1: "HOME"
%-------------------------------------------------------------------------%
CompStruct    = [];
CompStruct    = struct('Type',            'Button',        ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', 'toolHome_Open', ...
                       'PositionID',      1111,            ... % "1111" means TAB 1, SECTION 1, COLUMN 1, ROW 1
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'Open',         ...
                                                 'Icon', 'Icon.OPEN_24', ...
                                                 'ButtonPushedFcn', 'toolHome_OpenButtonPushed'));

%-------------------------------------------------------------------------%
% TAB 2: "PLOT"
%-------------------------------------------------------------------------%
% SECTION "PLAYBACK"
CompStruct(end+1) = struct('Type',        'Button',        ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_Play', ...
                       'PositionID',      2111,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Text', ' Play ',         ...
                                                 'Icon', 'play_24.png', ...
                                                 'ButtonPushedFcn', 'toolPlot_PlayButtonPushed'));

% SECTION "LIMITS"
CompStruct(end+1) = struct('Type',        'Spinner',       ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_xLim1', ...
                       'PositionID',      2211,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Limits', [0 6000], 'Value', 0, 'NumberFormat', 'double', 'DecimalFormat', '3f', 'ValueChangedFcn', 'toolPlot_xyLimitsCallbacks'));

CompStruct(end+1) = struct('Type',        'Spinner',       ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_yLim1', ...
                       'PositionID',      2212,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Limits', [-120 0], 'Value', -120, 'NumberFormat', 'double', 'DecimalFormat', '0f', 'ValueChangedFcn', 'toolPlot_xyLimitsCallbacks'));

CompStruct(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', 'toolPlot_xLimLabel', ...
                       'PositionID',      2221,            ...
                       'ColumnWidth',     '20',            ...
                       'ColumnHorAlign',  'center',        ...
                       'Parameters',      struct('Text', 'x '));

CompStruct(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', 'toolPlot_yLimLabel', ...
                       'PositionID',      2222,            ...
                       'ColumnWidth',     '20',            ...
                       'ColumnHorAlign',  'center',        ...
                       'Parameters',      struct('Text', 'y '));

CompStruct(end+1) = struct('Type',        'Spinner',       ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_xLim2', ...
                       'PositionID',      2231,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Limits', [0 6000], 'Value', 6000, 'NumberFormat', 'double', 'DecimalFormat', '3f', 'ValueChangedFcn', 'toolPlot_xyLimitsCallbacks'));

CompStruct(end+1) = struct('Type',        'Spinner',   ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_yLim2', ...
                       'PositionID',      2232,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Limits', [-120 0], 'Value', 0, 'NumberFormat', 'double', 'DecimalFormat', '0f', 'ValueChangedFcn', 'toolPlot_xyLimitsCallbacks'));

% SECTION "CONTROLS"
CompStruct(end+1) = struct('Type',        'ToggleButton',  ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', 'toolPlot_MinHold', ...
                       'PositionID',      2311,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'Min Hold',       ...
                                                 'Icon', 'MinHold_16.png', ...
                                                 'ValueChangedFcn', 'toolPlot_controlsCallbacks'));

CompStruct(end+1) = struct('Type',        'ToggleButton',  ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_Persistance', ...
                       'PositionID',      2312,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'Persistance',        ...
                                                 'Icon', 'Persistance_16.png', ...
                                                 'ValueChangedFcn', 'toolPlot_controlsCallbacks'));

CompStruct(end+1) = struct('Type',        'ToggleButton',  ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', 'toolPlot_Average', ...
                       'PositionID',      2321,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'Average',        ...
                                                 'Icon', 'Average_16.png', ...
                                                 'ValueChangedFcn', 'toolPlot_controlsCallbacks'));

CompStruct(end+1) = struct('Type',        'ToggleButton',  ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_OCC', ...
                       'PositionID',      2322,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'Occupancy',  ...
                                                 'Icon', 'OCC_16.png', ...
                                                 'ValueChangedFcn', 'toolPlot_controlsCallbacks'));

CompStruct(end+1) = struct('Type',        'ToggleButton',  ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', 'toolPlot_MaxHold', ...
                       'PositionID',      2331,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'Max Hold',       ...
                                                 'Icon', 'MaxHold_16.png', ...
                                                 'ValueChangedFcn', 'toolPlot_controlsCallbacks'));

CompStruct(end+1) = struct('Type',        'ToggleButton',   ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_Waterfall', ...
                       'PositionID',      2332,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'Waterfall',        ...
                                                 'Icon', 'Waterfall_16.png', ...
                                                 'ValueChangedFcn', 'toolPlot_controlsCallbacks'));


% % SECTION "PERSISTANCE"
% COLUMNS 1-2
CompStruct(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', 'toolPlot_winSizeLabel', ...
                       'PositionID',      2411,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'left',          ...
                       'Parameters',      struct('Text', 'Window size: '));

CompStruct(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', 'toolPlot_ColormapLabel', ...
                       'PositionID',      2412,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'left',         ...
                       'Parameters',      struct('Text', 'Colormap: '));

CompStruct(end+1) = struct('Type',        'DropDown',      ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_persistanceWinSize', ...
                       'PositionID',      2421,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Items', {{'128', '256', '512', 'full'}}, ...
                                                 'Value', 'full',                          ...
                                                 'ValueChangedFcn', 'toolPlot_persistanceCallbacks'));

CompStruct(end+1) = struct('Type',        'DropDown',      ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_persistanceColormap', ...
                       'PositionID',      2422,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Items', {{'winter', 'parula', 'turbo'}}, ...
                                                 'Value', 'winter',                        ...
                                                 'ValueChangedFcn', 'toolPlot_persistanceCallbacks'));


% COLUMNS 3-5
CompStruct(end+1) = struct('Type',        'Spinner',   ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_persistanceLim1', ...
                       'PositionID',      2431,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Limits', [0 100], 'Value', 0, 'NumberFormat', 'double', 'DecimalFormat', '3f', 'ValueChangedFcn', 'toolPlot_persistanceCallbacks'));

CompStruct(end+1) = struct('Type',        'ToggleButton',   ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', 'toolplot_persistanceRefresh', ...
                       'PositionID',      2432,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'c-Limits',       ...
                                                 'Icon', 'refresh_16.png', ...
                                                 'ValueChangedFcn', 'toolPlot_persistanceCallbacks'));

CompStruct(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '', ...
                       'PositionID',      2441,            ...
                       'ColumnWidth',     '10',          ...
                       'ColumnHorAlign',  'left',         ...
                       'Parameters',      struct('Text', 'c '));

CompStruct(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      2442,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',         ...
                       'Parameters',      struct('Text', ''));

CompStruct(end+1) = struct('Type',        'Spinner',   ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_persistanceLim2', ...
                       'PositionID',      2451,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Limits', [0 100], 'Value', 100, 'NumberFormat', 'double', 'DecimalFormat', '3f', 'ValueChangedFcn', 'toolPlot_persistanceCallbacks'));

CompStruct(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      2452,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',         ...
                       'Parameters',      struct('Text', ''));

% % SECTION "OCCUPANCY"
% COLUMNS 1-2
CompStruct(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', 'toolPlot_occTypeLabel', ...
                       'PositionID',      2511,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'left',          ...
                       'Parameters',      struct('Text', 'Threshold type: '));

CompStruct(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_occValueLabel', ...
                       'PositionID',      2512,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'left',         ...
                       'Parameters',      struct('Text', 'Value: '));

CompStruct(end+1) = struct('Type',        'DropDown',      ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_occType', ...
                       'PositionID',      2521,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Items', {{'linear', 'offset'}}, ...
                                                 'Value', 'linear',                        ...
                                                 'ValueChangedFcn', 'toolPlot_occCallbacks'));

CompStruct(end+1) = struct('Type',        'Spinner',   ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_occValue', ...
                       'PositionID',      2522,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Limits', [-120 0], 'Value', -80, 'NumberFormat', 'double', 'DecimalFormat', '0f', 'ValueChangedFcn', 'toolPlot_occCallbacks'));

% % SECTION "WATERFALL"
% COLUMNS 1-2
CompStruct(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', 'toolPlot_waterfallDirectionLabel', ...
                       'PositionID',      2611,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'left',          ...
                       'Parameters',      struct('Text', 'Direction: '));

CompStruct(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', 'toolPlot_waterfallColormapLabel', ...
                       'PositionID',      2612,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'left',         ...
                       'Parameters',      struct('Text', 'Colormap: '));

CompStruct(end+1) = struct('Type',        'DropDown',      ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_waterfallDirection', ...
                       'PositionID',      2621,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Items', {{'both', 'column', 'row'}}, ...
                                                 'Value', 'both',                      ...
                                                 'ValueChangedFcn', 'toolPlot_waterfallCallbacks'));

CompStruct(end+1) = struct('Type',        'DropDown',      ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_waterfallColormap', ...
                       'PositionID',      2622,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Items', {{'winter', 'parula', 'turbo'}}, ...
                                                 'Value', 'winter',                        ...
                                                 'ValueChangedFcn', 'toolPlot_waterfallCallbacks'));


% COLUMNS 3-5
CompStruct(end+1) = struct('Type',        'Spinner',   ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_waterfallLim1', ...
                       'PositionID',      2631,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Limits', [-120 0], 'Value', -120, 'NumberFormat', 'double', 'DecimalFormat', '0f', 'ValueChangedFcn', 'toolPlot_waterfallCallbacks'));

CompStruct(end+1) = struct('Type',        'ToggleButton',   ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', 'toolplot_waterfallRefresh', ...
                       'PositionID',      2632,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'c-Limits',       ...
                                                 'Icon', 'refresh_16.png', ...
                                                 'ValueChangedFcn', 'toolPlot_waterfallCallbacks'));

CompStruct(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '', ...
                       'PositionID',      2641,            ...
                       'ColumnWidth',     '10',          ...
                       'ColumnHorAlign',  'left',         ...
                       'Parameters',      struct('Text', 'c '));

CompStruct(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      2642,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',         ...
                       'Parameters',      struct('Text', ''));

CompStruct(end+1) = struct('Type',        'Spinner',   ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_waterfallLim2', ...
                       'PositionID',      2651,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Limits', [-120 0], 'Value', 0, 'NumberFormat', 'double', 'DecimalFormat', '0f', 'ValueChangedFcn', 'toolPlot_waterfallCallbacks'));

CompStruct(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      2652,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',         ...
                       'Parameters',      struct('Text', ''));

%-------------------------------------------------------------------------%
% TAB 3: "EMISSION"
%-------------------------------------------------------------------------%
% SECTION 1: "Add/List"
CompStruct(end+1) = struct('Type',        'Button',        ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      3111,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Text', ' Add  ',      ...
                                                 'Icon', 'Icon.ADD_24', ...
                                                 'ButtonPushedFcn', 'toolPlot_emissionAdd'));

CompStruct(end+1) = struct('Type',        'Button',        ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_emissionList', ...
                       'PositionID',      3121,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Text', ' List ',        ...
                                                 'Icon', 'Icon.LAYOUT_24', ...
                                                 'ButtonPushedFcn', 'toolPlot_emissionList'));

% SECTION 2: "Detection type"
CompStruct(end+1) = struct('Type',        'RadioButton', ...
                       'Group',           'emissionGroup1', ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      3211,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'Manual ROI', ...
                                                 'Value', true, ...
                                                 'ValueChangedFcn', 'toolPlot_emissionAddType'));

CompStruct(end+1) = struct('Type',        'RadioButton', ...
                       'Group',           'emissionGroup1', ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      3212,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'Automatic findpeaks', ...
                                                 'Value', false));

% SECTION 3: "FindPeaks parameters"
CompStruct(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      3311,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',         ...
                       'Parameters',      struct('Text', 'Number of peaks: '));

CompStruct(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      3312,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',         ...
                       'Parameters',      struct('Text', 'Prominence: '));

CompStruct(end+1) = struct('Type',        'Spinner',   ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_emissionNPeaks', ...
                       'PositionID',      3321,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Limits', [1 100], 'Value', 10, 'Enabled', false));

CompStruct(end+1) = struct('Type',        'Spinner',   ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_emissionProminence', ...
                       'PositionID',      3322,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Limits', [3 50], 'Value', 30, 'Enabled', false));

CompStruct(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      3331,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',         ...
                       'Parameters',      struct('Text', 'Separation: '));

CompStruct(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      3332,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',         ...
                       'Parameters',      struct('Text', 'Width: '));

CompStruct(end+1) = struct('Type',        'Spinner',   ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_emissionSeparation', ...
                       'PositionID',      3341,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Limits', [5 6000], 'Value', 25, 'Enabled', false));

CompStruct(end+1) = struct('Type',        'Spinner',   ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_emissionWidth', ...
                       'PositionID',      3342,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Limits', [0 100000], 'Value', 10, 'Enabled', false));

% SECTION 4: "Miscellaneous"
CompStruct(end+1) = struct('Type',        'Button',   ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', 'toolplot_emissionClassification', ...
                       'PositionID',      3411,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'Classification', ...
                                                 'Icon', 'list_16.png', ...
                                                 'ButtonPushedFcn', 'toolplot_emissionClassification'));

CompStruct(end+1) = struct('Type',        'Button',   ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', 'toolplot_emissionDriveTest', ...
                       'PositionID',      3412,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'Drive-test',     ...
                                                 'Icon', 'DriveTest_16.png', ...
                                                 'ButtonPushedFcn', 'toolplot_emissionDriveTest'));

%% New JSON file
writematrix(jsonencode(struct('Tab', TabStruct, 'Components', CompStruct), 'PrettyPrint', true), 'ConfigFile.json', 'FileType', 'text', 'QuoteStrings', 'none', 'WriteMode', 'overwrite')