% JSON Generator

%-------------------------------------------------------------------------%
% ## BUTTONS ##
%-------------------------------------------------------------------------%
% BUTTON
% C:\Program Files\MATLAB\R2022b\toolbox\matlab\toolstrip\+matlab\+ui\+internal\+toolstrip\Button.m
% Input arguments: "text", or "icon"
% btn = Button('Open', Icon.OPEN_24);
% btn.ButtonPushed = {@callbacks.openButtonPushed, this};

% DROPDOWNBUTTON / POPUPLIST / LISTITEM
% Input arguments: "text", or "icon"
% btn = matlab.ui.internal.toolstrip.DropDownButton(text,icon)
%
% sub_item1 = matlab.ui.internal.toolstrip.ListItem('Add Plot');
% sub_item1.ItemPushed = {@callbacks.subItem1Pushed, this};
% sub_item2 = matlab.ui.internal.toolstrip.ListItem('Delete Plot');
% sub_item2.ItemPushed = {@callbacks.subItem2Pushed, this};
%
% sub_popup = matlab.ui.internal.toolstrip.PopupList();
% sub_popup.add(sub_item1);
% sub_popup.add(sub_item2);
% 
% item1 = matlab.ui.internal.toolstrip.ListItem('Add Plot',matlab.ui.internal.toolstrip.Icon.ADD_16);
% item1.ItemPushed = {@callbacks.Item1Pushed, this};
%
% item2 = matlab.ui.internal.toolstrip.ListItemWithPopup('Delete Plot',matlab.ui.internal.toolstrip.Icon.CUT_16);
% item2.Popup = sub_popup;
% 
% popup = matlab.ui.internal.toolstrip.PopupList();
% popup.add(item1);
% popup.add(item2);
% 
% btn.Popup = popup;


% BUTTONGROUP - Radio buttons or toggle buttons in this group can only be selected one at a time.
% C:\Program Files\MATLAB\R2022b\toolbox\matlab\toolstrip\+matlab\+ui\+internal\+toolstrip\ButtonGroup.m
% group1 = ButtonGroup();
% btn1 = RadioButton(group1, 'Radio button 1');
% btn2 = RadioButton(group2, 'Radio button 2');

% TOGGLEBUTTON
% C:\Program Files\MATLAB\R2022b\toolbox\matlab\toolstrip\+matlab\+ui\+internal\+toolstrip\ToggleButton.m
% Input arguments: "text", "icon", or "group"
% btn = ToggleButton('Open', Icon.OPEN_24, Group1);
% btn.ValueChanged = {@callbacks.openButtonPushed, this};

% RADIOBUTTON
% C:\Program Files\MATLAB\R2022b\toolbox\matlab\toolstrip\+matlab\+ui\+internal\+toolstrip\RadioButton.m
% Input arguments: "group", and "text"
% btn = RadioButton(group, text);

TabStruct  = struct('HOME', {{'FILE', 'EDIT'}}, ...
                    'PLOT', {{'PLAYBACK', 'LIMITS', 'PERSISTANCE', 'WATERFALL'}});

% TAB "HOME"
CompStruct(1) = struct('Type',            'Button',        ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', 'toolHome_Open', ...
                       'PositionID',      1111,            ... % "1111" means TAB 1, SECTION 1, COLUMN 1, ROW 1
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'Open',         ...
                                                 'Icon', 'Icon.OPEN_24', ...
                                                 'ButtonPushedFcn', '@toolHome_OpenButtonPushed'));

% TAB "PLOT"
% SECTION "PLAYBACK"
CompStruct(2) = struct('Type',            'Button',        ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_Play', ...
                       'PositionID',      2111,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'Play',         ...
                                                 'Icon', 'play_24.png', ...
                                                 'ButtonPushedFcn', 'toolPlot_PlayButtonPushed'));

CompStruct(3) = struct('Type',            'ToggleButton',  ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', 'toolPlot_MinHold', ...
                       'PositionID',      2121,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'Min Hold',       ...
                                                 'Icon', 'MinHold_16.png', ...
                                                 'ValueChangedFcn', 'toolPlot_OperationButtonPushed'));

CompStruct(4) = struct('Type',            'ToggleButton',  ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', 'toolPlot_Average', ...
                       'PositionID',      2131,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'Average',        ...
                                                 'Icon', 'Average_16.png', ...
                                                 'ValueChangedFcn', 'toolPlot_OperationButtonPushed'));

CompStruct(5) = struct('Type',            'ToggleButton',  ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', 'toolPlotMaxHold', ...
                       'PositionID',      2141,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'Max Hold',       ...
                                                 'Icon', 'MaxHold_16.png', ...
                                                 'ValueChangedFcn', 'toolPlot_OperationButtonPushed'));

CompStruct(6) = struct('Type',            'ToggleButton',  ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', 'toolPlot_Persistance', ...
                       'PositionID',      2122,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'Persistance',        ...
                                                 'Icon', 'Persistance_16.png', ...
                                                 'ValueChangedFcn', 'toolPlot_OperationButtonPushed'));

CompStruct(7) = struct('Type',            'ToggleButton',  ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_OCC', ...
                       'PositionID',      2132,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'Occupancy',  ...
                                                 'Icon', 'OCC_16.png', ...
                                                 'ValueChangedFcn', 'toolPlot_OperationButtonPushed'));

CompStruct(8) = struct('Type',            'ToggleButton',   ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_Waterfall', ...
                       'PositionID',      2142,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'Waterfall',        ...
                                                 'Icon', 'Waterfall_16.png', ...
                                                 'ValueChangedFcn', 'toolPlot_OperationButtonPushed'));

% SECTION "LIMITS"
CompStruct(9) = struct('Type',            'Spinner',       ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_xLim1', ...
                       'PositionID',      2211,            ...
                       'ColumnWidth',     '70',            ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('ValueChangedFcn', 'toolPlot_xyLimSpinnerValueChanged'));

CompStruct(10) = struct('Type',           'Spinner',       ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_yLim1', ...
                       'PositionID',      2212,            ...
                       'ColumnWidth',     '70',            ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('ValueChangedFcn', 'toolPlot_xyLimSpinnerValueChanged'));

CompStruct(11) = struct('Type',           'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', 'toolPlot_xLimLabel', ...
                       'PositionID',      2221,            ...
                       'ColumnWidth',     '20',            ...
                       'ColumnHorAlign',  'center',        ...
                       'Parameters',      struct('Text', 'x'));

CompStruct(12) = struct('Type',           'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', 'toolPlot_yLimLabel', ...
                       'PositionID',      2222,            ...
                       'ColumnWidth',     '20',            ...
                       'ColumnHorAlign',  'center',        ...
                       'Parameters',      struct('Text', 'y'));

CompStruct(13) = struct('Type',           'Spinner',       ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_xLim2', ...
                       'PositionID',      2231,            ...
                       'ColumnWidth',     '70',            ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('ValueChangedFcn', 'toolPlot_xyLimSpinnerValueChanged'));

CompStruct(14) = struct('Type',            'Spinner',   ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'toolPlot_yLim2', ...
                       'PositionID',      2232,            ...
                       'ColumnWidth',     '70',            ...
                       'ColumnHorAlign',  'auto',          ...
                       'Parameters',      struct('ValueChangedFcn', 'toolPlot_xyLimSpinnerValueChanged'));