pathToMFILE   = fileparts(mfilename('fullpath'));

%-------------------------------------------------------------------------%
% TAB 1: "FILE"
%-------------------------------------------------------------------------%
TabStruct1  = struct('FILE',   {{'Read', 'Operations'}});
CompStruct1 = struct('Type',            'Button',        ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      1111,            ... % "1111" means TAB 1, SECTION 1, COLUMN 1, ROW 1
                       'ColumnWidth',     '40',            ...
                       'ColumnAlign',     'auto',          ...
                       'Parameters',      struct('Text', sprintf('Open\nFile'), ...
                                                 'Icon', 'Icon.OPEN_24',        ...
                                                 'ButtonPushedFcn', 'toolstrip.File_Open'));

CompStruct1(end+1) = struct('Type',        'Button',        ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'File_SpectralData', ...
                       'PositionID',      1121,            ...
                       'ColumnWidth',     '40',            ...
                       'ColumnAlign',     'auto',          ...
                       'Parameters',      struct('Text', sprintf('Spectral\nData'), ...
                                                 'Icon', 'playback_24.png',         ...
                                                 'Enabled', false,                  ...
                                                 'ButtonPushedFcn', 'toolstrip.File_SpectralData'));

CompStruct1(end+1) = struct('Type',        'Button',        ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      1211,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',     'auto',          ...
                       'Parameters',      struct('Text', 'Edit location', ...
                                                 'Icon', 'edit_16.png',   ...
                                                 'ButtonPushedFcn', 'toolstrip.File_Operations'));

CompStruct1(end+1) = struct('Type',        'Button',        ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      1212,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',     'auto',          ...
                       'Parameters',      struct('Text', 'Export',         ...
                                                 'Icon', 'Icon.EXPORT_16', ...
                                                 'ButtonPushedFcn', 'toolstrip.File_Operations'));


%-------------------------------------------------------------------------%
% TAB 2: "PLAYBACK"
%-------------------------------------------------------------------------%
% SECTION "PLAYBACK"
TabStruct2  = struct('PLAYBACK',   {{'Playback', 'xy-Limits', 'Controls', 'Persistance', 'Occupancy', 'Waterfall'}});
CompStruct2 = struct('Type',        'Button',        ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'Playback_Play', ...
                       'PositionID',      1111,            ...
                       'ColumnWidth',     '40',            ...
                       'ColumnAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'Play',        ...
                                                 'Icon', 'Icon.RUN_24', ...
                                                 'ButtonPushedFcn', 'toolstrip.Playback_Play'));

CompStruct2(end+1) = struct('Type',        'DropDownButton', ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', 'Playback_Save', ...
                       'PositionID',      1121,            ...
                       'ColumnWidth',     '40',          ...
                       'ColumnAlign',  'auto',          ...
                       'Parameters',      struct('Children', struct('Type', 'ListItem', ...
                                                                    'Parameters', struct('Text', 'Export image', ...
                                                                                         'Icon', 'Icon.EXPORT_16', ...
                                                                                         'ItemPushedFcn', 'toolstrip.Playback_Save')), ...
                                                 'Text', ' Save ', ...
                                                 'Icon', 'Icon.SAVE_24'));
CompStruct2(end).Parameters.Children(2) = struct('Type', 'ListItem', ...
                                                'Parameters', struct('Text', 'Save parameters', ...
                                                                     'Icon', 'report_16.png', ...
                                                                     'ItemPushedFcn', 'toolstrip.Playback_Save'));

% SECTION "XY-LIMITS"
CompStruct2(end+1) = struct('Type',        'Spinner',       ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'Playback_xLim1', ...
                       'PositionID',      1211,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnAlign',  'auto',          ...
                       'Parameters',      struct('Limits', [0 6000], 'Value', 0, 'NumberFormat', 'double', 'DecimalFormat', '3f', 'ValueChangedFcn', 'toolstrip.Playback_xyLimits'));

CompStruct2(end+1) = struct('Type',        'Spinner',       ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'Playback_yLim1', ...
                       'PositionID',      1212,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnAlign',  'auto',          ...
                       'Parameters',      struct('Limits', [-120 0], 'Value', -120, 'NumberFormat', 'double', 'DecimalFormat', '0f', 'ValueChangedFcn', 'toolstrip.Playback_xyLimits'));

CompStruct2(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      1221,            ...
                       'ColumnWidth',     '20',            ...
                       'ColumnAlign',  'center',        ...
                       'Parameters',      struct('Text', 'x '));

CompStruct2(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      1222,            ...
                       'ColumnWidth',     '20',            ...
                       'ColumnAlign',  'center',        ...
                       'Parameters',      struct('Text', 'y '));

CompStruct2(end+1) = struct('Type',        'Spinner',       ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'Playback_xLim2', ...
                       'PositionID',      1231,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnAlign',  'auto',          ...
                       'Parameters',      struct('Limits', [0 6000], 'Value', 6000, 'NumberFormat', 'double', 'DecimalFormat', '3f', 'ValueChangedFcn', 'toolstrip.Playback_xyLimits'));

CompStruct2(end+1) = struct('Type',        'Spinner',   ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'Playback_yLim2', ...
                       'PositionID',      1232,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnAlign',  'auto',          ...
                       'Parameters',      struct('Limits', [-120 0], 'Value', 0, 'NumberFormat', 'double', 'DecimalFormat', '0f', 'ValueChangedFcn', 'toolstrip.Playback_xyLimits'));

% SECTION "CONTROLS"
CompStruct2(end+1) = struct('Type',        'ToggleButton',  ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'Playback_MinHold', ...
                       'PositionID',      1311,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'Min Hold',       ...
                                                 'Icon', 'MinHold_16.png', ...
                                                 'ValueChangedFcn', 'toolstrip.Playback_Controls'));

CompStruct2(end+1) = struct('Type',        'ToggleButton',  ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'Playback_Persistance', ...
                       'PositionID',      1312,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'Persistance',        ...
                                                 'Icon', 'Persistance_16.png', ...
                                                 'ValueChangedFcn', 'toolstrip.Playback_Controls'));

CompStruct2(end+1) = struct('Type',        'ToggleButton',  ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'Playback_Average', ...
                       'PositionID',      1321,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'Average',        ...
                                                 'Icon', 'Average_16.png', ...
                                                 'ValueChangedFcn', 'toolstrip.Playback_Controls'));

CompStruct2(end+1) = struct('Type',        'ToggleButton',  ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'Playback_OCC', ...
                       'PositionID',      1322,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'Occupancy',  ...
                                                 'Icon', 'OCC_16.png', ...
                                                 'ValueChangedFcn', 'toolstrip.Playback_Controls'));

CompStruct2(end+1) = struct('Type',        'ToggleButton',  ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'Playback_MaxHold', ...
                       'PositionID',      1331,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'Max Hold',       ...
                                                 'Icon', 'MaxHold_16.png', ...
                                                 'ValueChangedFcn', 'toolstrip.Playback_Controls'));

CompStruct2(end+1) = struct('Type',        'ToggleButton',   ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'Playback_Waterfall', ...
                       'PositionID',      1332,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'Waterfall',        ...
                                                 'Icon', 'Waterfall_16.png', ...
                                                 'ValueChangedFcn', 'toolstrip.Playback_Controls'));


% SECTION "PERSISTANCE"
CompStruct2(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'Playback_winSizeLabel', ...
                       'PositionID',      1411,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',  'left',          ...
                       'Parameters',      struct('Text', 'Window size: '));

CompStruct2(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'Playback_ColormapLabel', ...
                       'PositionID',      1412,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',  'left',         ...
                       'Parameters',      struct('Text', 'Colormap: '));

CompStruct2(end+1) = struct('Type',        'DropDown',      ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'Playback_persistanceWinSize', ...
                       'PositionID',      1421,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnAlign',  'auto',          ...
                       'Parameters',      struct('Items', {{'128', '256', '512', 'full'}}, ...
                                                 'Value', 'full',                          ...
                                                 'ValueChangedFcn', 'toolstrip.Playback_Persistance'));

CompStruct2(end+1) = struct('Type',        'DropDown',      ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'Playback_persistanceColormap', ...
                       'PositionID',      1422,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnAlign',  'auto',          ...
                       'Parameters',      struct('Items', {{'winter', 'parula', 'turbo'}}, ...
                                                 'Value', 'winter',                        ...
                                                 'ValueChangedFcn', 'toolstrip.Playback_Persistance'));

CompStruct2(end+1) = struct('Type',        'Spinner',   ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'Playback_persistanceLim1', ...
                       'PositionID',      1431,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnAlign',  'auto',          ...
                       'Parameters',      struct('Limits', [0 100], 'Value', 0, 'NumberFormat', 'double', 'DecimalFormat', '3f', 'ValueChangedFcn', 'toolstrip.Playback_Persistance'));

CompStruct2(end+1) = struct('Type',        'ToggleButton',   ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', 'Playback_persistanceRefresh', ...
                       'PositionID',      1432,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'c-Limits',       ...
                                                 'Icon', 'refresh_16.png', ...
                                                 'ValueChangedFcn', 'toolstrip.Playback_Persistance'));

CompStruct2(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '', ...
                       'PositionID',      1441,            ...
                       'ColumnWidth',     '10',          ...
                       'ColumnAlign',  'left',         ...
                       'Parameters',      struct('Text', 'c '));

CompStruct2(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      1442,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',  'auto',         ...
                       'Parameters',      struct('Text', ''));

CompStruct2(end+1) = struct('Type',        'Spinner',   ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'Playback_persistanceLim2', ...
                       'PositionID',      1451,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnAlign',  'auto',          ...
                       'Parameters',      struct('Limits', [0 100], 'Value', 100, 'NumberFormat', 'double', 'DecimalFormat', '3f', 'ValueChangedFcn', 'toolstrip.Playback_Persistance'));

CompStruct2(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      1452,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',  'auto',         ...
                       'Parameters',      struct('Text', ''));

% SECTION "OCCUPANCY"
CompStruct2(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', 'Playback_occTypeLabel', ...
                       'PositionID',      1511,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',  'left',          ...
                       'Parameters',      struct('Text', 'Threshold type: '));

CompStruct2(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'Playback_occValueLabel', ...
                       'PositionID',      1512,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',  'left',         ...
                       'Parameters',      struct('Text', 'Value: '));

CompStruct2(end+1) = struct('Type',        'DropDown',      ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'Playback_occType', ...
                       'PositionID',      1521,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnAlign',  'auto',          ...
                       'Parameters',      struct('Items', {{'linear', 'offset'}}, ...
                                                 'Value', 'linear',                        ...
                                                 'ValueChangedFcn', 'toolstrip.Playback_Occupancy'));

CompStruct2(end+1) = struct('Type',        'Spinner',   ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'Playback_occValue', ...
                       'PositionID',      1522,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnAlign',  'auto',          ...
                       'Parameters',      struct('Limits', [-120 0], 'Value', -80, 'NumberFormat', 'double', 'DecimalFormat', '0f', 'ValueChangedFcn', 'toolstrip.Playback_Occupancy'));

% SECTION "WATERFALL"
CompStruct2(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      1611,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',  'left',          ...
                       'Parameters',      struct('Text', 'Direction: '));

CompStruct2(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      1612,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',  'left',         ...
                       'Parameters',      struct('Text', 'Colormap: '));

CompStruct2(end+1) = struct('Type',        'DropDown',      ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'Playback_waterfallDirection', ...
                       'PositionID',      1621,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnAlign',  'auto',          ...
                       'Parameters',      struct('Items', {{'both', 'column', 'row'}}, ...
                                                 'Value', 'both',                      ...
                                                 'ValueChangedFcn', 'toolstrip.Playback_Waterfall'));

CompStruct2(end+1) = struct('Type',        'DropDown',      ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'Playback_waterfallColormap', ...
                       'PositionID',      1622,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnAlign',  'auto',          ...
                       'Parameters',      struct('Items', {{'winter', 'parula', 'turbo'}}, ...
                                                 'Value', 'winter',                        ...
                                                 'ValueChangedFcn', 'toolstrip.Playback_Waterfall'));

CompStruct2(end+1) = struct('Type',        'Spinner',       ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'Playback_waterfallLim1', ...
                       'PositionID',      1631,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnAlign',  'auto',          ...
                       'Parameters',      struct('Limits', [-120 0], 'Value', -120, 'NumberFormat', 'double', 'DecimalFormat', '0f', 'ValueChangedFcn', 'toolstrip.Playback_Waterfall'));

CompStruct2(end+1) = struct('Type',        'ToggleButton',  ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', 'Playback_waterfallRefresh', ...
                       'PositionID',      1632,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',  'auto',          ...
                       'Parameters',      struct('Text', 'c-Limits',       ...
                                                 'Icon', 'refresh_16.png', ...
                                                 'ValueChangedFcn', 'toolstrip.Playback_Waterfall'));

CompStruct2(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '', ...
                       'PositionID',      1641,            ...
                       'ColumnWidth',     '10',          ...
                       'ColumnAlign',  'left',         ...
                       'Parameters',      struct('Text', 'c '));

CompStruct2(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      1642,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',  'auto',         ...
                       'Parameters',      struct('Text', ''));

CompStruct2(end+1) = struct('Type',        'Spinner',   ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'Playback_waterfallLim2', ...
                       'PositionID',      1651,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnAlign',  'auto',          ...
                       'Parameters',      struct('Limits', [-120 0], 'Value', 0, 'NumberFormat', 'double', 'DecimalFormat', '0f', 'ValueChangedFcn', 'toolstrip.Playback_Waterfall'));

CompStruct2(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      1652,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',  'auto',         ...
                       'Parameters',      struct('Text', ''));

 
%-------------------------------------------------------------------------%
% TAB 3: "REPORT"
%-------------------------------------------------------------------------%
% SECTION 1: "Report"
TabStruct3  = struct('REPORT', {{'Report', 'Detection', 'Findpeaks parameters', 'Classification', 'Drive-test'}});
CompStruct3 = struct('Type',        'Button',            ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      1111,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',     'auto',          ...
                       'Parameters',      struct('Text', ' Run  ',      ...
                                                 'Icon', 'Icon.RUN_24', ...
                                                 'ButtonPushedFcn', 'toolstrip.Report_Run'));

% SECTION 2: "Detection"
CompStruct3(end+1) = struct('Type',        'Button',        ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      1211,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',     'auto',          ...
                       'Parameters',      struct('Text', sprintf('Add\nEmission'),      ...
                                                 'Icon', 'Icon.NEW_24', ...
                                                 'ButtonPushedFcn', 'toolstrip.Report_AddEmission'));

CompStruct3(end+1) = struct('Type',        'RadioButton', ...
                       'Group',           'emissionGroup1', ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      1221,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',     'auto',          ...
                       'Parameters',      struct('Text', 'Automatic findpeaks', ...
                                                 'Value', true));

CompStruct3(end+1) = struct('Type',        'RadioButton', ...
                       'Group',           'emissionGroup1', ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      1222,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',     'auto',          ...
                       'Parameters',      struct('Text', 'Manual ROI', ...
                                                 'Value', false, ...
                                                 'ValueChangedFcn', 'toolstrip.Report_DetectionType'));


% Section 3: Findpeaks parameters
CompStruct3(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      1311,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',     'auto',         ...
                       'Parameters',      struct('Text', 'Number of peaks: '));

CompStruct3(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      1312,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',     'auto',         ...
                       'Parameters',      struct('Text', 'Prominence (dB): '));

CompStruct3(end+1) = struct('Type',        'Spinner',   ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'Report_emissionNPeaks', ...
                       'PositionID',      1321,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnAlign',     'auto',          ...
                       'Parameters',      struct('Limits', [1 100], 'Value', 10));

CompStruct3(end+1) = struct('Type',        'Spinner',   ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'Report_emissionProminence', ...
                       'PositionID',      1322,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnAlign',     'auto',          ...
                       'Parameters',      struct('Limits', [3 50], 'Value', 30));

CompStruct3(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      1331,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',     'auto',         ...
                       'Parameters',      struct('Text', 'Separation (kHz): '));

CompStruct3(end+1) = struct('Type',        'Label',         ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', '',              ...
                       'PositionID',      1332,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',     'auto',         ...
                       'Parameters',      struct('Text', 'Width (kHz): '));

CompStruct3(end+1) = struct('Type',        'Spinner',   ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'Report_emissionSeparation', ...
                       'PositionID',      1341,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnAlign',     'auto',          ...
                       'Parameters',      struct('Limits', [5 6000], 'Value', 25));

CompStruct3(end+1) = struct('Type',        'Spinner',   ...
                       'Group',           '',              ...
                       'appProperty',     1,               ...
                       'appPropertyName', 'Report_emissionWidth', ...
                       'PositionID',      1342,            ...
                       'ColumnWidth',     '90',            ...
                       'ColumnAlign',     'auto',          ...
                       'Parameters',      struct('Limits', [0 100000], 'Value', 10));

% SECTION 4: "Classification"
CompStruct3(end+1) = struct('Type',        'Button',        ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', 'Report_emissionClassification', ...
                       'PositionID',      1411,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',     'auto',          ...
                       'Parameters',      struct('Text', 'Classification', ...
                                                 'Icon', 'list_16.png', ...
                                                 'ButtonPushedFcn', 'toolstrip.Report_Classification'));

CompStruct3(end+1) = struct('Type',        'Button',        ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', 'Report_emissionDatabase', ...
                       'PositionID',      1412,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',     'auto',          ...
                       'Parameters',      struct('Text', 'Database', ...
                                                 'Icon', 'database_16.png', ...
                                                 'ButtonPushedFcn', 'toolstrip.Report_Database'));

% SECTION 5: "Drive-test"
CompStruct3(end+1) = struct('Type',        'Button',        ...
                       'Group',           '',              ...
                       'appProperty',     0,               ...
                       'appPropertyName', 'Report_emissionDriveTest', ...
                       'PositionID',      1511,            ...
                       'ColumnWidth',     'auto',          ...
                       'ColumnAlign',     'auto',          ...
                       'Parameters',      struct('Text', 'Drive-test',     ...
                                                 'Icon', 'DriveTest_24.png', ...
                                                 'ButtonPushedFcn', 'toolstrip.Report_DriveTest'));


%-------------------------------------------------------------------------%
% FILES
%-------------------------------------------------------------------------%
writematrix(jsonencode(struct('Tab', TabStruct1, 'Components', CompStruct1), 'PrettyPrint', true), fullfile(pathToMFILE, '+toolstrip', 'toolstrip_ConfigFile_FILE.json'),     'FileType', 'text', 'QuoteStrings', 'none', 'WriteMode', 'overwrite')
writematrix(jsonencode(struct('Tab', TabStruct2, 'Components', CompStruct2), 'PrettyPrint', true), fullfile(pathToMFILE, '+toolstrip', 'toolstrip_ConfigFile_PLAYBACK.json'), 'FileType', 'text', 'QuoteStrings', 'none', 'WriteMode', 'overwrite')
writematrix(jsonencode(struct('Tab', TabStruct3, 'Components', CompStruct3), 'PrettyPrint', true), fullfile(pathToMFILE, '+toolstrip', 'toolstrip_ConfigFile_REPORT.json'),   'FileType', 'text', 'QuoteStrings', 'none', 'WriteMode', 'overwrite')