function File_TreeSelectionChanged(src, event, app)

    idx1 = [];
    idx2 = [];
    for ii = 1:numel(app.File_Tree.SelectedNodes)
        idx1 = [idx1, app.File_Tree.SelectedNodes(ii).NodeData.idx1];
        idx2 = [idx2, app.File_Tree.SelectedNodes(ii).NodeData.idx2];
    end

    idx1 = unique(idx1);
    idx2 = unique(idx2);

    app.File_Metadata.HTMLSource = ' ';
    if (numel(idx1) == 1) && (numel(idx2) == 1)
        app.File_Metadata.HTMLSource = MetadataInfo(app, idx1, idx2);
    end
end


%-------------------------------------------------------------------------%
function htmlCode = MetadataInfo(app, idx1, idx2)

    gpsData = app.metaData(idx1).Data(idx2).GPS;
    if gpsData.Status
        if gpsData.Count > 1
            gpsMessage = sprintf(['\n\n<b>GPS DATA</b>\n'                                                                 ...
                                  '• <span style="color: #808080;">Samples:</span> %d\n'                                  ...
                                  '• <span style="color: #808080;">Latitude (µ ± σ):</span> %.6f ± %.6f\n'                ...
                                  '• <span style="color: #808080;">Longitude (µ ± σ):</span> %.6f ± %.6f\n'               ...
                                  '• <span style="color: #808080;">Coordinates within interval (µ ± σ):</span> %.0f%%\n'  ...
                                  '• <span style="color: #808080;">Coordinates within interval (µ ± 2σ):</span> %.0f%%\n' ...
                                  '• <span style="color: #808080;">Coordinates within interval (µ ± 3σ):</span> %.0f%%\n' ...
                                  '• <span style="color: #808080;">Location: </span> %s (%s)'],                           ...
                                  gpsData.Count,                                                 ...
                                  gpsData.Latitude,  gpsData.Latitude_std,                       ...
                                  gpsData.Longitude, gpsData.Longitude_std,                      ...
                                  gpsData.stdRange(1), gpsData.stdRange(2), gpsData.stdRange(3), ...
                                  gpsData.Location, gpsData.LocationSource);
        else
            gpsMessage = sprintf(['\n\n<b>GPS DATA</b>\n'                                        ...
                                  '• <span style="color: #808080;">Samples:</span> %d\n'         ...
                                  '• <span style="color: #808080;">Latitude:</span> %.6f\n'      ...
                                  '• <span style="color: #808080;">Longitude:</span> %.6f\n'     ...
                                  '• <span style="color: #808080;">Location: </span> %s (%s)'],  ...
                                  gpsData.Count,                                                 ...
                                  gpsData.Latitude,                                              ...
                                  gpsData.Longitude,                                             ...
                                  gpsData.Location, gpsData.LocationSource);
        end
    end

    htmlCode = sprintf(['<font style="font-family: Helvetica; font-size: 11px;">'      ...
                        '<b>TASK</b>\n'                                                ...
                       '• <span style="color: #808080;">Receiver:</span> %s\n'         ...
                       '• <span style="color: #808080;">FreqStart:</span> %.3f MHz\n'  ...
                       '• <span style="color: #808080;">FreqStop:</span> %.3f MHz\n'   ...
                       '• <span style="color: #808080;">Resolution:</span> %.3f kHz\n' ...
                       '• <span style="color: #808080;">Unit:</span> %s\n'             ...
                       '• <span style="color: #808080;">TraceMode:</span> %s\n'        ...
                       '• <span style="color: #808080;">TraceIntegration:</span> %d\n' ...
                       '• <span style="color: #808080;">Detector:</span> %s\n'         ...                       
                       '• <span style="color: #808080;">Antenna:</span> %s\n\n'        ...
                       '<b>SPECTRAL DATA</b>\n'                                        ...
                       '• <span style="color: #808080;">Samples:</span> %d\n'          ...
                       '• <span style="color: #808080;">ObservationTime:</span> %s'    ...
                       '%s</font>'],                                                   ...
                       app.metaData(idx1).Data(idx2).Receiver,                   ...
                       app.metaData(idx1).Data(idx2).MetaData.FreqStart  / 1e+6, ...
                       app.metaData(idx1).Data(idx2).MetaData.FreqStop   / 1e+6, ...
                       app.metaData(idx1).Data(idx2).MetaData.Resolution / 1e+3, ...
                       app.metaData(idx1).Data(idx2).MetaData.LevelUnit,         ...
                       app.metaData(idx1).Data(idx2).MetaData.TraceMode,         ...
                       app.metaData(idx1).Data(idx2).MetaData.TraceIntegration,  ...
                       app.metaData(idx1).Data(idx2).MetaData.Detector,          ...
                       app.metaData(idx1).Data(idx2).MetaData.Antenna,           ...
                       app.metaData(idx1).Data(idx2).Samples,                    ...
                       app.metaData(idx1).Data(idx2).ObservationTime,            ...
                       gpsMessage);

    htmlCode = replace(htmlCode, newline, '<br>');
end