function SpectralData_TreeSelectionChanged(src, event, app)

    idx = unique([app.SpectralData_Tree.SelectedNodes.NodeData]);

    app.SpectralData_Metadata.HTMLSource = ' ';
    if (numel(idx) == 1)
        app.SpectralData_Metadata.HTMLSource = MetadataInfo(app, idx);
        panel.Emission_TreeSelectionChanged([], [], app, idx)
    end
end


%-------------------------------------------------------------------------%
function htmlCode = MetadataInfo(app, idx)

    gpsData = app.specData(idx).GPS;
    if gpsData.Status
        if gpsData.Count > 1
            gpsMessage = sprintf(['\n\n<b>GPS DATA</b>\n'                                                                 ...
                                  '• <span style="color: #808080;">Samples:</span> %d\n'                                  ...
                                  '• <span style="color: #808080;">Latitude (µ ± σ):</span> %.6f ± %.6f\n'                ...
                                  '• <span style="color: #808080;">Longitude (µ ± σ):</span> %.6f ± %.6f\n'               ...
                                  '• <span style="color: #808080;">Coordinates within interval (µ ± σ):</span> %.0f%%\n'  ...
                                  '• <span style="color: #808080;">Coordinates within interval (µ ± 2σ):</span> %.0f%%\n' ...
                                  '• <span style="color: #808080;">Coordinates within interval (µ ± 3σ):</span> %.0f%%\n' ...
                                  '• <span style="color: #808080;">Location: </span> %s (%s)'],                           ...
                                  gpsData.Count,                                                 ...
                                  gpsData.Latitude,  gpsData.Latitude_std,                       ...
                                  gpsData.Longitude, gpsData.Longitude_std,                      ...
                                  gpsData.stdRange(1), gpsData.stdRange(2), gpsData.stdRange(3), ...
                                  gpsData.Location, gpsData.LocationSource);
        else
            gpsMessage = sprintf(['\n\n<b>GPS DATA</b>\n'                                        ...
                                  '• <span style="color: #808080;">Samples:</span> %d\n'         ...
                                  '• <span style="color: #808080;">Latitude:</span> %.6f\n'      ...
                                  '• <span style="color: #808080;">Longitude:</span> %.6f\n'     ...
                                  '• <span style="color: #808080;">Location: </span> %s (%s)'],  ...
                                  gpsData.Count,                                                 ...
                                  gpsData.Latitude,                                              ...
                                  gpsData.Longitude,                                             ...
                                  gpsData.Location, gpsData.LocationSource);
        end
    end

    htmlCode = sprintf(['<font style="font-family: Helvetica; font-size: 11px;">'      ...
                       '<b>FILE</b>\n'                                                 ...
                       '%s\n\n'                                                        ...        
                       '<b>TASK</b>\n'                                                 ...
                       '• <span style="color: #808080;">Receiver:</span> %s\n'         ...
                       '• <span style="color: #808080;">FreqStart:</span> %.3f MHz\n'  ...
                       '• <span style="color: #808080;">FreqStop:</span> %.3f MHz\n'   ...
                       '• <span style="color: #808080;">Resolution:</span> %.3f kHz\n' ...
                       '• <span style="color: #808080;">Unit:</span> %s\n'             ...
                       '• <span style="color: #808080;">TraceMode:</span> %s\n'        ...
                       '• <span style="color: #808080;">TraceIntegration:</span> %d\n' ...
                       '• <span style="color: #808080;">Detector:</span> %s\n'         ...                       
                       '• <span style="color: #808080;">Antenna:</span> %s\n\n'        ...
                       '<b>SPECTRAL DATA</b>\n'                                        ...
                       '• <span style="color: #808080;">Samples:</span> %d\n'          ...
                       '• <span style="color: #808080;">ObservationTime:</span> %s'    ...
                       '%s</font>'],                                                   ...
                       strjoin("• " + app.specData(idx).RelatedFiles.Name, '\n'),      ...
                       app.specData(idx).Receiver,                   ...
                       app.specData(idx).MetaData.FreqStart  / 1e+6, ...
                       app.specData(idx).MetaData.FreqStop   / 1e+6, ...
                       app.specData(idx).MetaData.Resolution / 1e+3, ...
                       app.specData(idx).MetaData.LevelUnit,         ...
                       app.specData(idx).MetaData.TraceMode,         ...
                       app.specData(idx).MetaData.TraceIntegration,  ...
                       app.specData(idx).MetaData.Detector,          ...
                       app.specData(idx).MetaData.Antenna,           ...
                       app.specData(idx).Samples,                    ...
                       app.specData(idx).ObservationTime,            ...
                       gpsMessage);

    htmlCode = replace(htmlCode, newline, '<br>');
end