function Read_metaData(app, ii)
    
    [~, name, ext] = fileparts(app.metaData(ii).File);
    
    switch lower(ext)
        case '.bin'
            fileID = fopen(app.metaData(ii).File);
            Format = fread(fileID, [1 36], '*char');
            fclose(fileID);

            if contains(Format, 'CRFS', "IgnoreCase", true)
                app.metaData(ii).Data = fileReader.CRFSBin(app.metaData(ii).File, 'MetaData', []);
            elseif contains(Format, 'RFlookBin v.1/1', "IgnoreCase", true)
                app.metaData(ii).Data = fileReader.RFLookBin(app.metaData(ii).File, 'MetaData');
            elseif contains(Format, 'RFlookBin v.2/1', "IgnoreCase", true)
                app.metaData(ii).Data = fileReader.RFlookBinV2(app.metaData(ii).File, 'MetaData');
            else
                error('The file indicated below does not seem to be generated by Logger or appColeta.\n• %s', [name ext])
            end
        
        case '.dbm'
            app.metaData(ii).Data = fileReader.CellPlanDBM(app.metaData(ii).File, 'MetaData', [], app.RootFolder);

        case '.sm1809'
            app.metaData(ii).Data = fileReader.SM1809(app.metaData(ii).File, 'MetaData', []);
            
        case '.csv'
            app.metaData(ii).Data = fileReader.ArgusCSV(app.metaData(ii).File, 'SingleFile', []);

        case '.mat'
            load(app.metaData(ii).File, '-mat', 'prj_metaData')
            app.metaData(ii).Data = prj_metaData;                
    end
    
    if isempty([app.metaData(ii).Data.Samples])
        error('The file indicated below does not contain spectral information.\n• %s', [name ext])
    end
    
    app.metaData(ii).Samples = [app.metaData(ii).Data.Samples]';
    app.metaData(ii).Memory  = EstimatedMemory(app, ii);    
end


%-------------------------------------------------------------------------%
function result = EstimatedMemory(app, ii)
    result = 0;
    for jj = 1:numel(app.metaData(ii).Data)
        result = result + 4 * app.metaData(ii).Data(jj).Samples .* app.metaData(ii).Data(jj).MetaData.DataPoints .* 1e-6;
    end    
end